site_name: ogajduse's docs
site_description: "Personal documentation site containging mostly braindumps."
site_author: "Ondřej Gajdušek"
docs_dir: docs/
repo_name: "ogajduse/docs.gajdusek.dev"
repo_url: "https://github.com/ogajduse/docs.gajdusek.dev"
nav:
  - Home: index.md
  - Bash Help: bash_help.md
  - Linux Commands: linux-commands.md
  - Monitoring:
      - Graphite: monitoring/graphite.md
  - Packaging:
      - Getting packages from repository manually: packaging/getting-repo-packages.md
      - RPM Packaging: packaging/rpm-packaging.md
  - My Projects:
      - How to migrate activities from Sports Tracker to Strava: my_projects/how-to-migrate-from-sports-tracker-to-strava.md
  - Foreman:
      - Discourse API Key Generator: foreman/discourse-api-key.md
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
